To : debian-devel <debian-devel@lists.debian.org>
Subject : Re: Moving away from (unsupportable) FusionForge on Alioth?
From : Boyuan Yang <073plan@gmail.com>
Date : Mon, 15 May 2017 15:54:25 +0800
Message-id : 1741002.0fvW30uaEj@hosiet-tp
In-reply-to : <[🔎] 8737c7vzad.fsf@sergiodj.net>
References : <[🔎] 2427425.7kBbIdvgt6@hosiet-tp> <[🔎] 4630781.jpJ1j7pWS5@hosiet-tp> <[🔎] 8737c7vzad.fsf@sergiodj.net>


在 2017年5月14日星期日 +08 下午6:39:22，Sergio Durigan Junior 写道：
> On Sunday, May 14 2017, Boyuan Yang wrote:
> > 在 2017年5月14日星期日 CST 下午3:04:26，Pirate Praveen 写道：
> > 
> >> As far as I understand, the only thing that is blocking is non
> >> availability of pagure package.
> >> 
> >> So helping fix this would help move this forward (currently pagure tests
> >> are failing).
> >> 
> >> >> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829046
> >> 
> >> After we have the package, then DSA standard processes for new service
> >> would follow, I assume.
> Sure.  I'll move everything to collab-maint as soon as I get back home,
> as I said earilier.
That would be great.
> >> Could you tell me where can I find the proper packaging repository?
> > 
> > I have pushed my copy here
> > https://git.fosscommunity.in/praveen/pagure
> > 
> > It was originally at git://git.sergiodj.net/debian/pagure-new.git
> 
> Thanks for doing that.
I took a look into pagure packaging (both upstream latest version 2.14.2 and 
Debian packaging version 2.6+dfsg from the git repo above) and things look 
like a nightmare. Under Debian Testing and Debian Unstable, current packaging 
did not create a working database for unittests. If we create db manually 
(before dh_auto_test) and run unittest again, things can fail severely (around 
60+/290+ units fail, not just 5). 
Hence it would be great if anyone familiar with Python2 and Flask could help 
improve the status of pagure packaging.
--
Boyuan Yangsignature.asc